[project]
name = "mcp-copilot-studio"
version = "0.1.0"
description = "MCP server for the agents built using Copilot studio"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.6.0",
]
